-- USER SQL
CREATE USER PLSQL_EXCEPTION_LOGGING IDENTIFIED BY "oracle"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER PLSQL_EXCEPTION_LOGGING QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "CONNECT" TO PLSQL_EXCEPTION_LOGGING ;
ALTER USER PLSQL_EXCEPTION_LOGGING DEFAULT ROLE "CONNECT";

-- SYSTEM PRIVILEGES
GRANT CREATE TRIGGER TO PLSQL_EXCEPTION_LOGGING ;
GRANT CREATE SEQUENCE TO PLSQL_EXCEPTION_LOGGING ;
GRANT CREATE VIEW TO PLSQL_EXCEPTION_LOGGING ;
GRANT CREATE SESSION TO PLSQL_EXCEPTION_LOGGING ;
GRANT SELECT ANY TABLE TO PLSQL_EXCEPTION_LOGGING ;
GRANT CREATE TABLE TO PLSQL_EXCEPTION_LOGGING ;
GRANT CREATE TYPE TO PLSQL_EXCEPTION_LOGGING ;
GRANT CREATE PUBLIC SYNONYM TO PLSQL_EXCEPTION_LOGGING ;
GRANT CREATE SEQUENCE TO PLSQL_EXCEPTION_LOGGING ;
GRANT CREATE PROCEDURE TO PLSQL_EXCEPTION_LOGGING ;

